version: '3'

networks:
  selenium:
    driver: bridge

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium

  chrome-node:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    links:
      - selenium-hub
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5555/wd/hub/status" ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - selenium

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chrome-node
    volumes:
      - ./src:/usr/src/app/src
      - ./pom.xml:/usr/src/app/pom.xml
      - ./src/test/resources:/usr/src/app/src/test/resources
    networks:
      - selenium
